/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siswa;

/**
 *
 * @author sypri
 */
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import siswa.Koneksi;

public class siswaform extends javax.swing.JFrame {

    DefaultTableModel model;
    private boolean isEditMode = false;
    private String selectedNim = null;

    /**
     * Creates new form siswaform
     */
    public siswaform() {
        initComponents();
        createTableIfNotExists();
        tampilData();
    }

    private void createTableIfNotExists() {
        try (Connection conn = Koneksi.getConnection()) {
            String sql = "CREATE TABLE IF NOT EXISTS siswa ("
                    + "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                    + "nama TEXT, nim TEXT, alamat TEXT, jenis_kelamin TEXT)";
            Statement stmt = conn.createStatement();
            stmt.execute(sql);
        } catch (SQLException e) {
            System.out.println("Gagal membuat tabel: " + e.getMessage());
        }
    }

    private void tampilData() {
        model = (DefaultTableModel) Tabel_Siswa.getModel();
        model.setRowCount(0); // Kosongkan tabel
        try (Connection conn = Koneksi.getConnection()) {
            String sql = "SELECT * FROM siswa";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString("nama"),
                    rs.getString("nim"),
                    rs.getString("alamat"),
                    rs.getString("jenis_kelamin")
                });
            }
        } catch (SQLException e) {
            System.out.println("Gagal menampilkan data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNama_Siswa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txt_Nim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_Alamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Slc_Jenis_kelamin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Siswa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama siswa");

        jLabel2.setText("Nim");

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis kelmin");

        Slc_Jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));

        Tabel_Siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama Siswa", "Nim", "Alamat", "Jenis Kelamin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel_Siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_SiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Siswa);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Data Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnSimpan.setBackground(new java.awt.Color(0, 51, 204));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNama_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Txt_Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Txt_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(Slc_Jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slc_Jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabel_SiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_SiswaMouseClicked
        int row = Tabel_Siswa.getSelectedRow();
        if (evt.getClickCount() == 1 && row != -1) {
            String nama = Tabel_Siswa.getValueAt(row, 1).toString();
            String nim = Tabel_Siswa.getValueAt(row, 2).toString();
            String alamat = Tabel_Siswa.getValueAt(row, 3).toString();
            String jk = Tabel_Siswa.getValueAt(row, 4).toString();

            int pilihan = javax.swing.JOptionPane.showOptionDialog(
                    this,
                    "Pilih aksi untuk data:\nNIM: " + nim + "\nNama: " + nama,
                    "Aksi Data",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.INFORMATION_MESSAGE,
                    null,
                    new String[]{"Edit", "Hapus", "Batal"},
                    "Edit"
            );

            if (pilihan == 0) { // Edit
                txtNama_Siswa.setText(nama);
                Txt_Nim.setText(nim);
                Txt_Alamat.setText(alamat);
                Slc_Jenis_kelamin.setSelectedItem(jk);

                isEditMode = true;
                selectedNim = nim;
                btnSimpan.setText("Update");

            } else if (pilihan == 1) { // Hapus
                int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                        this, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

                if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                    try (Connection conn = Koneksi.getConnection()) {
                        String sql = "DELETE FROM siswa WHERE nim=?";
                        PreparedStatement pst = conn.prepareStatement(sql);
                        pst.setString(1, nim);
                        pst.executeUpdate();
                        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                        tampilData();
                    } catch (SQLException e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
                    }
                }
            }
            // Batal → Tidak lakukan apa pun
        }
    }//GEN-LAST:event_Tabel_SiswaMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama_Siswa.getText();
        String nim = Txt_Nim.getText();
        String alamat = Txt_Alamat.getText();
        String jk = Slc_Jenis_kelamin.getSelectedItem().toString();

        if (nama.isEmpty() || nim.isEmpty() || alamat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Isi semua field!");
            return;
        }

        try (Connection conn = Koneksi.getConnection()) {
            if (isEditMode) {
                // UPDATE
                String sql = "UPDATE siswa SET nama=?, nim=?, alamat=?, jenis_kelamin=? WHERE nim=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setString(2, nim);
                pst.setString(3, alamat);
                pst.setString(4, jk);
                pst.setString(5, selectedNim); // WHERE nim lama
                pst.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            } else {
                // INSERT
                String sql = "INSERT INTO siswa(nama, nim, alamat, jenis_kelamin) VALUES (?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setString(2, nim);
                pst.setString(3, alamat);
                pst.setString(4, jk);
                pst.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            }

            tampilData();
            clearInput();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    private void clearInput() {
        txtNama_Siswa.setText("");
        Txt_Nim.setText("");
        Txt_Alamat.setText("");
        Slc_Jenis_kelamin.setSelectedIndex(0);
        isEditMode = false;
        selectedNim = null;
        btnSimpan.setText("Simpan");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswaform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Slc_Jenis_kelamin;
    private javax.swing.JTable Tabel_Siswa;
    private javax.swing.JTextField Txt_Alamat;
    private javax.swing.JTextField Txt_Nim;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNama_Siswa;
    // End of variables declaration//GEN-END:variables
}
